runtime: nodejs20
service: default

automatic_scaling:
   min_idle_instances: 0
   max_idle_instances: 1
   min_instances: 0
   max_instances: 1

handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|otf|map|webp))
    static_files: dist/\1
    upload: dist/.*

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
