/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertComponent: typeof import('./components/AlertComponent.vue')['default']
    GraficaZapatos: typeof import('./components/GraficaZapatos.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MenuComponent: typeof import('./components/MenuComponent.vue')['default']
    NavigationComponent: typeof import('./components/NavigationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonComponent: typeof import('./components/SkeletonComponent.vue')['default']
    SnackBarComponent: typeof import('./components/SnackBarComponent.vue')['default']
  }
}
